<a href="https://colab.research.google.com/github/2303A53030/HumeraMahaveen-B-46/blob/main/LAB0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a1=np.array([[1,2,3],[4,5,6]])
print(a1)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(a1.dtype)

int64


In [ ]:
print(a1.size)

6


In [ ]:
print(a1.shape)

(2, 3)


In [ ]:
a2=a1.flatten()
print(a2)

[1 2 3 4 5 6]


In [ ]:
a3=a1.reshape(3,2)
print(a3)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
m1=np.matrix('1,2,3;4,5,6')
print(m1)

[[1 2 3]
 [4 5 6]]


In [ ]:
m2=np.matrix('7,8,9;2,4,5')
print(m2)

[[7 8 9]
 [2 4 5]]


In [ ]:
m3=m1+m2
print(m3)

[[ 8 10 12]
 [ 6  9 11]]


In [ ]:
a=np.matrix('8,4,5;1,6,8;5,1,2')
print(a)

[[8 4 5]
 [1 6 8]
 [5 1 2]]


In [ ]:
b=np.matrix('6,1,9;4,6,5;7,1,3')
print(b)

[[6 1 9]
 [4 6 5]
 [7 1 3]]


In [ ]:
c=a*b
print(c)

[[ 99  37 107]
 [ 86  45  63]
 [ 48  13  56]]


In [ ]:
print(c.min())

13


In [ ]:
print(c.max())

107
